<?php
// backend/send_receipt.php
declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');
ini_set('display_errors', '0');

require __DIR__ . '/../../vendor/autoload.php';

use Dotenv\Dotenv;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

try {
  // Load env (project root)
  if (file_exists(__DIR__ . '/../../.env')) {
    Dotenv::createImmutable(__DIR__ . '/../../')->load();
  } elseif (file_exists(__DIR__ . '/../.env')) {
    Dotenv::createImmutable(__DIR__ . '/..')->load();
  }

  // Read JSON body from the page
  $raw = file_get_contents('php://input');
  if (!$raw) throw new RuntimeException('Empty body');
  $req = json_decode($raw, true);
  if (!is_array($req)) throw new RuntimeException('Invalid JSON');

  $to = trim((string)($req['to'] ?? ''));
  $payload = $req['payload'] ?? null;   // { order: {...}, items: [...] }

  if (!filter_var($to, FILTER_VALIDATE_EMAIL)) {
    throw new RuntimeException('Valid email required');
  }
  if (!is_array($payload) || !isset($payload['order'])) {
    throw new RuntimeException('Missing order payload');
  }

  $o = $payload['order'];
  $items = $payload['items'] ?? [];

  // Build a simple HTML email
  $fmt = fn($n, $d=2) => is_numeric($n) ? number_format((float)$n, $d) : '0';
  ob_start();
  ?>
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;max-width:640px;margin:auto;">
    <h2 style="margin:0 0 12px;">NutriPOS Receipt</h2>
    <div style="color:#666;margin-bottom:12px;">
      <div><strong>Order:</strong> <?= htmlspecialchars($o['id'] ?? '') ?></div>
      <div><strong>Date:</strong> <?= htmlspecialchars($o['created_at'] ?? '') ?> UTC</div>
    </div>

    <h3 style="margin:16px 0 8px;">Nutrition summary</h3>
    <table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse">
      <tr><td>Energy</td><td style="text-align:right;"><?= $fmt($o['energy_kj'],1) ?> kJ (<?= $fmt($o['calories_kcal'],0) ?> kcal)</td></tr>
      <tr><td>Protein</td><td style="text-align:right;"><?= $fmt($o['protein_g']) ?> g</td></tr>
      <tr><td>Fat</td><td style="text-align:right;"><?= $fmt($o['fat_g']) ?> g</td></tr>
      <tr><td>Carbohydrate</td><td style="text-align:right;"><?= $fmt($o['carb_g']) ?> g</td></tr>
      <tr><td>Sugars</td><td style="text-align:right;"><?= $fmt($o['sugars_g']) ?> g</td></tr>
      <tr><td>Sodium</td><td style="text-align:right;"><?= $fmt($o['sodium_mg'],0) ?> mg</td></tr>
    </table>

    <?php if (!empty($items)): ?>
    <h3 style="margin:20px 0 8px;">Items</h3>
    <table cellpadding="6" cellspacing="0" style="width:100%;border-collapse:collapse;border:1px solid #eee">
      <thead>
        <tr style="background:#fafafa">
          <th align="left">Name</th>
          <th align="left">Code</th>
          <th align="right">Grams</th>
          <th align="right">Qty</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($items as $it): ?>
        <tr style="border-top:1px solid #eee">
          <td><?= htmlspecialchars($it['name'] ?? '') ?></td>
          <td><?= htmlspecialchars($it['afcd_code'] ?? '') ?></td>
          <td align="right"><?= $fmt($it['grams'] ?? 0, 0) ?></td>
          <td align="right"><?= htmlspecialchars((string)($it['qty'] ?? 1)) ?></td>
        </tr>
        <?php if (!empty($it['ingredients']) && is_array($it['ingredients'])): ?>
          <tr>
            <td colspan="4" style="color:#666;font-size:13px;">
              <ul style="margin:6px 0 0 18px;padding:0;">
                <?php foreach ($it['ingredients'] as $ing): ?>
                  <li>
                    <?= $fmt($ing['grams'] ?? 0, 0) ?> g – 
                    <?= htmlspecialchars($ing['name'] ?? 'Ingredient') ?>
                    <?= !empty($ing['afcd_code']) ? ' ['.htmlspecialchars($ing['afcd_code']).']' : '' ?>
                  </li>
                <?php endforeach; ?>
              </ul>
            </td>
          </tr>
        <?php endif; ?>
      <?php endforeach; ?>
      </tbody>
    </table>
    <?php endif; ?>

    <div style="margin-top:18px;color:#888;font-size:12px;">
      Generated by NutriPOS
    </div>
  </div>
  <?php
  $html = ob_get_clean();

require '../vendor/autoload.php';

$mail = new PHPMailer(true);

try {
    // Server settings
    $mail->isSMTP();
    $mail->Host       = $_ENV['SMTP_HOST'];
    $mail->SMTPAuth   = true;
    $mail->Username   = $_ENV['SMTP_USER'];
    $mail->Password   = $_ENV['SMTP_PASS'];
    $mail->SMTPSecure = $_ENV['SMTP_SECURE']; // 'tls'
    $mail->Port       = $_ENV['SMTP_PORT'];

    // Recipients
    $mail->setFrom($_ENV['MAIL_FROM'], $_ENV['MAIL_FROM_NAME']);
    $mail->addAddress("customer@example.com", "Customer Name"); // pull from order DB

    // Content
    $mail->isHTML(true);
    $mail->Subject = "Your NutriPOS Receipt";
    $mail->Body    = file_get_contents(__DIR__ . "/receipt_template.html"); 
    $mail->AltBody = "Please view this receipt in HTML format.";

    $mail->send();
    echo "Receipt email sent!";
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";

  }  
}

